{
 "title": "Node_Load",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_MONITORING", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_boot_time{app=\"prometheus-node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max Uptime (selected nodes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_time{instance=~\"(${node:pipe}).*\"} - node_boot_time{instance=~\"(${node:pipe}).*\"})"
    }
   ]
  },
  {
   "title": "Average Uptime (selected nodes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_time{instance=~\"(${node:pipe}).*\"} - node_boot_time{instance=~\"(${node:pipe}).*\"})/count(node_boot_time{instance=~\"(${node:pipe}).*\"})"
    }
   ]
  },
  {
   "title": "Total RAM (selected nodes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal{instance=~\"(${node:pipe}).*\"})"
    }
   ]
  },
  {
   "title": "Total CPU Cores (selected nodes)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(node_cpu{instance=~\"(${node:pipe}).*\"}) by (cpu,instance))"
    }
   ]
  },
  { "title": "Node Spec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Node CPU Usage ($node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "Percent Usage %" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu{instance=~\"$node:9100\",mode=~\"system|irq|softirq\"}[5m])) * 100)",
     "legendFormat": "System"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu{instance=~\"$node:.*\",mode=\"user\"}[5m])) * 100)",
     "legendFormat": "User"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu{instance=~\"$node:.*\",mode=\"iowait\"}[5m])) * 100)",
     "legendFormat": "I/O Wait"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu{instance=~\"$node:.*\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Node System Load ($node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"(${node:pipe}).*\"}",
     "legendFormat": "Load5"
    }
   ]
  },
  {
   "title": "Network I/O ($node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes{instance=~\"$node.*\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes{instance=~\"$node.*\"}[5m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Node Disk I/O ($node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed{instance=~\"$node:.*\", device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}}:{{app}}"
    }
   ]
  }
 ]
}