{
 "title": "PBR Namespace Memory Usage 2",
 "tags": [ "top-level" ],
 "time": { "from": "2018-04-25T19:09:21.274Z", "to": "2018-04-25T19:09:33.096Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_memory_usage_bytes,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Routing Cores",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{Role=\"PBR\",pod_name!~\"calico.*\",pod_name!~\"node-exporter.*\",pod_name!~\"kube-proxy.*\",pod_name!=\"\"}[60s]))  "
    }
   ]
  },
  {
   "title": "Total Routing Memory",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "decgbytes",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{Role=\"PBR\",pod_name!~\"calico.*\",pod_name!~\"node-exporter.*\",pod_name!~\"kube-proxy.*\",pod_name!=\"\"}) / 1000000000"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1.2, "x": 0, "y": 7 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[60s])) * 1000 "
    }
   ]
  },
  {
   "title": "$namespace",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 1.2, "x": 0, "y": 16 },
   "repeat": "namespace",
   "format": "gbytes",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=~\"$namespace\", Role=\"PBR\",pod_name!~\"calico.*\",pod_name!~\"node-exporter.*\",pod_name!~\"kube-proxy.*\",pod_name!=\"\"}) / 1000000000"
    }
   ]
  }
 ]
}