{
 "title": "Pod Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_MONITORING", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "TOP 10 CPU hungry PODs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (pod_name)( rate(container_cpu_usage_seconds_total{pod_name!=\"\"}[1m] ) )))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Top 10 Ram hungry PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(container_memory_usage_bytes{pod_name!=\"\"}) by (pod_name)))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}